#!/bin/bash

DIR="./src/utils"

OUT_FILE="./src/allUtils.ts"

>"$OUT_FILE"
echo "// autogenerated by generateUtil.sh script\n" -e >"$OUT_FILE"

for file in "$DIR"/*.ts; do
    # Extract filename without path and extension
    filename=$(basename "$file" .ts)
    echo "export * from \"./utils/$filename\"" >>"$OUT_FILE"
done
